---
title: "preprocessing"
format: html
editor: visual
---

```{r}
library(readr)
library(tidyverse)
library(readxl)
library(here)
```


```{r}
#| label: read-in-wellcome-data

crosstabs <- read_excel(here("wgm2018.xlsx"), sheet=1, skip=2)
full_data <- read_excel(here("wgm2018.xlsx"), sheet=2)
dictionary <- read_excel(here("wgm2018.xlsx"), sheet=3)
#this is cleaned data for q1 specifically
cleaned <- read.csv(here("wgm_cleaned.csv"))



```

# data for high trust in scientists %

```{r}
#| label: clean crosstabs data
q2data <- crosstabs %>%
fill(Question, .direction="down") %>%
  filter(Question == "Wellcome Global Monitor Trust in Scientists Index (recoded into 3 categories)", Response == "High trust") %>%
  mutate(`Column N %...4` = round(`Column N %...4`,4)) %>%
  rename(`High trust in scientists %` = `Column N %...4`) %>%
  select(1,4)

# Remove the trailing comma
text <- sub(",$", "", dictionary[1,3])

# Split by comma
parts <- strsplit(text, ",\\s*")[[1]]

parts <- as_tibble(parts)

country_codes <- separate_wider_delim(parts, value, delim = "=",
                                      names = c("code", "Country"))

cleaned_codes <- left_join(q2data, country_codes, by = "Country")

countries_regions <- full_data %>%
  select(WP5, Regions_Report) %>%
  rename("code" = "WP5") %>%
  mutate(code = as.character(code),
         Regions_Report = as.character(Regions_Report))

clean_regions <- left_join(cleaned_codes, countries_regions, by = "code") %>%
  distinct() 

text <- sub(",$", "", dictionary[57,3])

# Split by comma
parts <- strsplit(text, ",\\s*")[[1]]

parts <- as_tibble(parts)

region_codes <- separate_wider_delim(parts, value, delim = "=",
                                     names = c("Regions_Report", "Region"))

cleaned_codes <- left_join(clean_regions, region_codes, by = "Regions_Report")

q2clean <- cleaned_codes %>%
  mutate(Region = replace_na(Region, "Not assigned")) %>%
  select(-c(code, Regions_Report))
```

```{r}
write_csv(q2clean, "scientist_high_trust.csv")
```

# trust in scientists for cards
```{r}

trust_props <- crosstabs %>%
fill(Question, .direction="down") %>%
  filter(Question == "Wellcome Global Monitor Trust in Scientists Index (recoded into 3 categories)", Response %in% c("Low trust", "Medium trust", "High trust", "DK/Refused")) %>%
  mutate(`Column N %...4` = round(`Column N %...4`,4)) %>%
  rename(`Weighted_prop` = `Column N %...4`,
         `Unweighted count` = `Unweighted Count...5`) %>%
  select(1,3,4,5) 
```

```{r}
write_csv(trust_props, "scientist_trust_props.csv")
```


# vaccine safety
```{r}
# Remove the trailing comma
text <- sub(",$", "", dictionary[1,3])

# Split by comma
parts <- strsplit(text, ",\\s*")[[1]]

parts <- as_tibble(parts)

country_codes <- separate_wider_delim(parts, value, delim = "=", 
                                      names = c("code", "country"))

cleaned_codes <- left_join(cleaned, country_codes, by = "country")

countries_regions <- full_data %>%
  select(WP5, Regions_Report) %>%
  rename("code" = "WP5") %>%
  mutate(code = as.character(code))

clean_regions <- left_join(cleaned_codes, countries_regions, by = "code") %>%
  distinct() 


grouped <- clean_regions %>%
  group_by(country) %>%
  mutate(pct_vaccines_safe = sum(National.results[answer %in% 
                                                    c("Strongly agree", "Somewhat agree")]) / 1) %>%
  select(country, pct_vaccines_safe, Regions_Report) %>%
  distinct() %>%
  mutate(Region = case_when(
    Regions_Report %in% c(1, 2, 4, 5) ~ "Africa",
    Regions_Report %in% c(6, 7, 8) ~ "Americas",
    Regions_Report %in% c(9, 10, 11, 12, 18) ~ "Asia",
    Regions_Report %in% c(3, 13) ~ "Middle East and North Africa",
    Regions_Report %in% c(15, 16, 17, 0) ~ "Europe",
    Regions_Report == 14 ~ "Former Soviet Union"
  )) %>%
  select(-Regions_Report) %>%
  filter(!is.na(Region))
```

```{r}
write_csv(grouped, "vaccine_safety.csv")
```


# vaccine efficiency

```{r}
#| label: clean/grab data for part 3

q3data <- crosstabs %>%
  fill(Question, .direction="down") %>%
  filter(Question == "Q26 Do you strongly or somewhat agree, strongly or somewhat disagree or neither agree nor disagree with the following statement? Vaccines are effective.") %>%
  rename(`Proportion` = `Column N %...4`) %>%
  select(1, 3:5)
```

```{r}
# Remove the trailing comma
text <- sub(",$", "", dictionary[1,3])

# Split by comma
parts <- strsplit(text, ",\\s*")[[1]]

parts <- as_tibble(parts)

country_codes <- separate_wider_delim(parts, value, delim = "=",
                                      names = c("code", "Country"))

cleaned_codes <- left_join(q3data, country_codes, by = "Country")

countries_regions <- full_data %>%
  select(WP5, Regions_Report) %>%
  rename("code" = "WP5") %>%
  mutate(code = as.character(code),
         Regions_Report = as.character(Regions_Report))

clean_regions <- left_join(cleaned_codes, countries_regions, by = "code") %>%
  distinct() 
```

```{r}
# Remove the trailing comma
text <- sub(",$", "", dictionary[57,3])

# Split by comma
parts <- strsplit(text, ",\\s*")[[1]]

parts <- as_tibble(parts)

region_codes <- separate_wider_delim(parts, value, delim = "=",
                                     names = c("Regions_Report", "Region"))

cleaned_codes <- left_join(clean_regions, region_codes, by = "Regions_Report")

q3clean <- cleaned_codes %>%
  mutate(Region = replace_na(Region, "Not assigned")) %>%
  select(-c(Proportion,code,Regions_Report)) %>%
  filter(Response != "Total") %>%
  rename(Counts = `Unweighted Count...5`)
```

```{r}
write_csv(q3clean, "vaccine_efficiency.csv")
```


```{r}
region_response_props <- q3clean %>%
  group_by(Region, Response) %>%
  summarise(RegionCounts = sum(Counts)) %>%
  mutate(Proportion = RegionCounts / sum(RegionCounts))

region_response_props <- region_response_props %>%
   mutate(Response = factor(Response, levels = c(
    "Strongly agree",
    "Somewhat agree",
    "Neither agree nor disagree",
    "Somewhat disagree",
    "Strongly disagree",
    "Don't know/Refused"
  )))
```

```{r}
label_data <- region_response_props %>%
  group_by(Region) %>%
  slice_max(RegionCounts, n = 1) %>%  
  ungroup()
```

```{r}

```

# vaccine info for cards

```{r}
#| label: Table of proportions for vaccine safety
#| title: Are vaccines safe?
safe_props <- crosstabs %>%
fill(Question, .direction="down") %>%
  filter(Question == "Q25 Do you strongly or somewhat agree, strongly or somewhat disagree or neither agree nor disagree with the following statement? Vaccines are safe.", Response %in% c("Strongly agree", "Somewhat agree", 
                                       "Neither agree nor disagree", 
                                       "Somewhat disagree", "Strongly disagree",
                                       "Don't know/Refused")) %>%
  mutate(`Column N %...4` = round(`Column N %...4`,4)) %>%
  rename(`Weighted_prop` = `Column N %...4`,
         `Unweighted count` = `Unweighted Count...5`) %>%
  select(1,3,4,5) 

safe_props %>% gt()
```

```{r}
write_csv(safe_props, "safe_props.csv")
```


```{r}
#| title: Are vaccines effective?
#| label: Table of proportions for vaccine efficiency
effective_props <- crosstabs %>%
fill(Question, .direction="down") %>%
  filter(Question == "Q26 Do you strongly or somewhat agree, strongly or somewhat disagree or neither agree nor disagree with the following statement? Vaccines are effective.", Response %in% c("Strongly agree", "Somewhat agree", 
                                       "Neither agree nor disagree", 
                                       "Somewhat disagree", "Strongly disagree",
                                       "Don't know/Refused")) %>%
  mutate(`Column N %...4` = round(`Column N %...4`,4)) %>%
  rename(`Weighted_prop` = `Column N %...4`,
         `Unweighted count` = `Unweighted Count...5`) %>%
  select(1,3,4,5) 

effective_props %>% gt()
```

```{r}
write_csv(effective_props, "effective_props.csv")
```

